# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

# firebase ish added by davis 06/25

target 'Login-Screen' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Login-Screen
  pod 'Firebase/Core'

end
