# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# firebase ish added by davis 06/25
pod 'Firebase/Core'

target 'Login-Screen' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Login-Screen

  target 'Login-ScreenTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Login-ScreenUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
